### ISSUE TITLE
Hi, this is not an issue, but i cant find anyway to do it

### ISSUE THREAD

**Issue by GuiTheDev** [TheHunterManX/GBA-PK-multiplayer#24]
Hey, i want to chat with the creator of this script. Do you have any contact info(discord is preference)? Anyway my discord is GuiTheDev#7276 .
Please contact me when able

Glowing Regards
-----------------
Guilherme Macedo

**Comment by televisionia** [comment]
I might not be the creator, but have you taken a look at the setup video https://www.youtube.com/watch?v=Nu4Yb7vOx0k ? You're better off posting a issue asking how to or looking through other issues instead of trying to contact the creator. It's more convenient.
By the way, for setting up the server, I'm assuming you cant be bothered with port forwarding. I recommend using something like a Hamachi network and connecting you and your friend to the same network, and changing the IP in the script to the IP given from the network. Zerotier is a very good alternative, especially cross-platform, I've tested with a friend that was on mac and it was successful! It's like using virtual networks for setting up Minecraft LAN servers with your friends without needing to be in the same wifi, but instead its Firered/Leafgreen multiplayer.

**Comment by GuiTheDev** [comment]
I don't want his contacts to report issues, I do want to talk with him, but for other completly diffrent topics.

**Comment by televisionia** [comment]
Ah, alright

**Comment by TheHunterManX** [comment]
Just read this now, I'll contact you.
