### ISSUE TITLE
Issues using playit.gg

### ISSUE THREAD

**Issue by rotigod** [TheHunterManX/GBA-PK-multiplayer#33]
I usually use playit.gg as my replacement for port forwarding but I have seem to have hit a roadblock as I entered the port provided but cannot connect to the server, below are the port used and ip used to connect to the server, I dont know whether it is the protocol used or incorrect entering of the ip in the client file being "147.185.221.211:55476", 4096. Tried without the port to no avail .

![Capture](https://user-images.githubusercontent.com/78321072/211179238-a18d164e-1fa2-4787-9840-698555abf072.PNG)

**Comment by Oraceon** [comment]
In order to connect to a server hosted on non-LAN connection, the server needs to be port forwarded using the IPv4 (private IP address) and using an available port. In this case, it looks like the port is 55476. Keep in mind that this port if it is not working may be being used by another program on your PC, which will cause a port conflict. Alternatively, if you changed the lua script to use the port 55476, be certain to also change the IP in the script to the Public IP address, not the IPv4 address. You can lookup your public IP address by going to a website such as: https://www.ipchicken.com/

**Comment by minigamerking** [comment]
> In order to connect to a server hosted on non-LAN connection, the server needs to be port forwarded using the IPv4 (private IP address) and using an available port. In this case, it looks like the port is 55476. Keep in mind that this port if it is not working may be being used by another program on your PC, which will cause a port conflict. Alternatively, if you changed the lua script to use the port 55476, be certain to also change the IP in the script to the Public IP address, not the IPv4 address. You can lookup your public IP address by going to a website such as: https://www.ipchicken.com/

I know that im necro replying to this post, but I tried doing this, set the ip field to my computers public ip and the port to the one that was opened by playit.gg, yet it won't connect. I also checked to see if there was a port conflict and there wasn't. Is there anything else im missing?
