### ISSUE TITLE
[BUG]: GBA-PK_Client Skript crashes emulator

### ISSUE THREAD

**Issue by olfrie** [TheHunterManX/GBA-PK-multiplayer#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

After using GBA-PK_Client Skript the emulator froze and crashed shortly afterwards, this happend on the pc of me and my friend while the GBA--PK ServerSkript worked perfectly fine. 

### Steps To Reproduce

Open mGBA
Insert Pokemon Fire Red
Load the Skript GBA-PK_Client 
Emulator crashes

**Comment by ArtMatters** [comment]
This happens when the client cannot connect to the server. If the server is reachable it should not crash. This is still a problem though. It tries to connect a bit too frequently I would assume and lags the game client out. This also means if the host loses connection or crashes the clients will crash as well.

As for now try having the server host load their script first, and then connect. If it is still crashing your port forwarding may be configured incorrectly.

**Comment by TheHunterManX** [comment]
Yep, this is due to client unable to connect to server.
