### ISSUE TITLE
Battling NPCs

### ISSUE THREAD

**Issue by dlhayden44** [TheHunterManX/GBA-PK-multiplayer#44]
I saw SmallAnt's video about this and in his and his friend's game the NPCs would only ever fight one of them then were defeated. Me and my brother got it all to work but the NPCs fight both of us. Wondering how to make ours so only one can fight them so it feels more like we are in the same game or maybe I misunderstood. Thanks

**Comment by televisionia** [comment]
I would assume that they were just waiting for each other to finish just so it was easier for the viewers to watch (imagine having two battles running and recorded at once!) the script is more or so a illusion that just draws the other players on the screen, no collision, and just hide when they aren't on the same map as you. Plus with a bonus that allows you to trade with your friend. Maybe you might have misunderstood and the editing of the video might have mislead you.  

But yeah, I think it would be a bit chaotic with collision on large amounts of players, people would be able to block areas and it would be kind of annoying not being able to fight someone because some other player is.

**Comment by dlhayden44** [comment]
Oh... ok sounds good, thanks!

**Comment by Kelonics** [comment]
The only thing is in the video: https://youtu.be/UeKxAYVkOHE?t=488

they show him walking past the trainer not having to battle it after the other guy already beat him. this is also all done on livestream too, I'm just assuming its a feature that SmallAnts amazing developer Atsign added!
