### ISSUE TITLE
How to use with mobile? And a few other questions

### ISSUE THREAD

**Issue by HierarchyMan** [TheHunterManX/GBA-PK-multiplayer#47]
I was absolutely stunned by your work. You're doing an amazing job
But is there a way to host the server completely on mobile and then join the server using mobile?
Also what does the person with the client lua have to do? does he have to load into a new game or his own save or is he stored in the savefile of the server? 
Will the person who's joining the server have their progress saved? And where?

**Comment by televisionia** [comment]
How this script works is that it's more or so a illusion where clients send their location and character data to the server and its sent back to the other clients. The other players are just drawn in the screen, it's not a ROM hack of some sort. Which also means your save data works the exact same as if you were playing by yourself (which is handy because you can continue your save without having to be connected to a server.) The way saves work do not change, again, it's just an illusion of it looking like they are in the same game as you. With the addition of being able to trade of course, which I don't know the technical details of, but also probably works through transferring data between clients.

About playing on mobile, mgba is not on android (neither IOS but you wouldn't use a iphone for game emulation) but there IS a retroarch mgba core, so you can technically use mgba on android. However I'm not sure if the scripting feature is on the mgba core for retroarch, which is required to even be able to use the script in the first place.

**Comment by HierarchyMan** [comment]
Thankyou for the helpful answer. I will surely check out mgba on retroarch
