### ISSUE TITLE
I might not be the creator, but have you taken a look at the setup video https://www.youtube.com/watch?v=Nu4Yb7vOx0k ? You're better off posting a issue asking how to or looking through other issues instead of trying to contact the creator. It's more convenient.

### ISSUE THREAD

**Issue by eherna6373** [TheHunterManX/GBA-PK-multiplayer#60]
I might not be the creator, but have you taken a look at the setup video https://www.youtube.com/watch?v=Nu4Yb7vOx0k ? You're better off posting a issue asking how to or looking through other issues instead of trying to contact the creator. It's more convenient.
By the way, for setting up the server, I'm assuming you cant be bothered with port forwarding. I recommend using something like a Hamachi network and connecting you and your friend to the same network, and changing the IP in the script to the IP given from the network. Zerotier is a very good alternative, especially cross-platform, I've tested with a friend that was on mac and it was successful! It's like using virtual networks for setting up Minecraft LAN servers with your friends without needing to be in the same wifi, but instead its Firered/Leafgreen multiplayer.

_Originally posted by @televisionia in https://github.com/TheHunterManX/GBA-PK-multiplayer/issues/24#issuecomment-1343965888_
            

I'm trying to portforward, could you help me?

**Comment by televisionia** [comment]
That's something google can help you for.

You'll need access to configuring your router settings and the settings are different depending on your router. Figure out what kind of router you have then look up how to port forward on it. Having a separate device to run the server would be helpful as well, just keep in mind running it from home might be unsecure since you might have to share the public IP address of your device. I suggest just using ZeroTier to do a virtual network.

**Comment by TheHunterManX** [comment]
Thank you.
